server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  profiles.active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: lib
    password: 5834
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        id:
#          new_generator_mappings=false:
